### ISSUE TITLE
Erro no carregamento de novos serviços

### ISSUE THREAD

**Issue by isaacvits** [servicosgovbr/portal-de-servicos#551]
Quando um editor cria um novo serviço e publica, ele não aparece no portal de serviços.

**Comment by cv** [comment]
TODO: encontrar stacktrace do ElasticSearch durante a inicialização do Portal em produção

**Comment by cv** [comment]
Analisando o stack trace, parece que o índice do ES foi corrompido, e ele não conseguiu mais funcionar direito depois disso:

```
[2016-01-22 23:52:07,074][DEBUG][action.search.type       ] [es1] All shards failed for phase: [dfs]
org.elasticsearch.transport.RemoteTransportException: [es2][inet[/172.17.0.3:9300]][indices:data/read/search[phase/dfs]]
Caused by: org.elasticsearch.indices.IndexMissingException: [pds-importador] missing
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:288)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:559)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
	at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:223)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:757)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:748)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cv** [comment]
Será que a gente consegue liberar o Kibana pra eu conseguir visualizar a ordem das operações que aconteceram durante a (re)importação em produção?

**Comment by isaacvits** [comment]
@cv vou verificar com a DTI porque não estamos acessando o kibana.

**Comment by isaacvits** [comment]
@cv verifiquei o Kibana do ambiente de produção e ocorreu um erro na hora de mostrar as operações:

**Discover: An error occurred with your request. Reset your inputs and try again** 

O acesso a porta 5601 do Kibana é apenas na rede interna do MP.

**Comment by cv** [comment]
Isso pode ser mais um indício de que os índices do ElasticSearch em produção estão com problemas :disappointed: 

Vocês conseguem ver o log do Kibana, particularmente quando acontece esse erro?

**Comment by isaacvits** [comment]
Vou te enviar o log do kibana.

**Comment by isaacvits** [comment]
O kibana no desenvolvimento está rodando normalmente.

O kibana do produção está com problema no índice do logstash, continuando com o erro acima: **Discover: An error occurred with your request. Reset your inputs and try again**
